name: GPAS create docker container

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: login to OCR
        uses: docker/login-action@v2 
        with:
          registry: lhr.ocir.io
          username: ${{ secrets.OCR_USERNAME }}
          password: ${{ secrets.OCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./environments/Dockerfile
          tags: |
            lhr.ocir.io/${{secrets.OCR_NAMESPACE}}/oxfordmmm/clockwork_bcftools:latest
            lhr.ocir.io/${{secrets.OCR_NAMESPACE}}/oxfordmmm/clockwork_bcftools:${{env.RELEASE_VERSION}}
          push: true
          no-cache: true
      - name: Docker digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Scan image
        uses: anchore/scan-action@v3
        id: imagescan
        with:
          image: "lhr.ocir.io/${{secrets.OCR_NAMESPACE}}/oxfordmmm/clockwork_bcftools:latest"
          fail-build: false
      - name: upload Anchore Image scna SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.imagescan.outputs.sarif }}